GoodWareMixWebClient/Controllers/ComparisonController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using GoodWareMixWebClient.Model;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.IO;

namespace GoodWareMixWebClient.Controllers
{
    public class ComparisonController : Controller
    {
        private readonly ILogger<ComparisonController> _logger;
        private readonly INotyfService _notyf;
        public ComparisonController(ILogger<ComparisonController> logger, INotyfService notyf)
        {
            _logger = logger;
            _notyf = notyf;
        }

        private IFormFile formFile;

        [RequestSizeLimit(Int32.MaxValue)]
        public async Task<IActionResult> Index(string supplierName, IFormFile file)
        {
            if (file != null)
            {
                FileInfo fileInfo = new FileInfo(file.FileName);
                HttpClient client = new HttpClient();
                client.Timeout = TimeSpan.FromMinutes(5);
                client.BaseAddress = new Uri(Connection.DefaultConnection);
                using var requestContext = new MultipartFormDataContent();

                requestContext.Add(new StreamContent(file.OpenReadStream()), "file", file.FileName);
                HttpResponseMessage message = await client.PostAsync($"{Connection.DefaultConnection}api/product/InternalCodeBinding/{supplierName}", requestContext);
                string RepsonseAsJson = await message.Content.ReadAsStringAsync();
                if (message.IsSuccessStatusCode)
                {
                    _notyf.Success("Импорт запущен", 10);
                    //List<string> ls = JsonConvert.DeserializeObject<List<string>>(RepsonseAsJson);
                    //foreach (var item in ls)
                    //{
                    //    ViewBag.Result += item + "\n";
                    //}
                }
                else
                {
                    _notyf.Error($"Ошибка запуска", 10);
                }
                return RedirectToAction("Index", "Supplier");
            }
            else
            {
                if (supplierName != null)
                {
                    HttpClient client = new HttpClient();
                    client.BaseAddress = new Uri(Connection.DefaultConnection);
                    HttpResponseMessage response = await client.GetAsync($"{Connection.DefaultConnection}api/Supplier/{supplierName}");
                    string json = await response.Content.ReadAsStringAsync();
                    var supplier = JsonConvert.DeserializeObject<ProFileSupplier>(json);
                    if (supplier != null)
                    {
                        return View(supplier);
                    }
                    else { return View(); }
                }
                else { return View(); }
            }
        }


        // GET: ComparsionController
        [HttpPost]
        public async Task<IActionResult> LoadFile(string supplierName, IFormFile file)
        {
            HttpClient client = new HttpClient();
            client.Timeout = TimeSpan.FromMinutes(5);
            HttpContent? content = null;
            HttpContent cn = (HttpContent)file;


            HttpResponseMessage response = await client.PostAsync($"{Connection.DefaultConnection}api/InternalCodeBinding?supplierName={supplierName}", content);

            if (response.IsSuccessStatusCode)
            {
                _notyf.Success($"Задача для {supplierName} запущена", 10);
                return RedirectToAction("Index", "Supplier");
            }
            else
            {
                _notyf.Error("Ошибка запуска", 10);
                return RedirectToAction("Index", "Supplier");
            }
        }

        // GET: ComparsionController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ComparsionController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ComparsionController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ComparsionController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ComparsionController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ComparsionController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ComparsionController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

GoodWareMixWebClient/Views/Comparison/Index.cshtml
<div class="page-wrapper">
	<div class="page-content">
        <h4>Сопоставление внутренних кодов из 1С @Model.SupplierName</h4>
        <form asp-action="Index" asp-controller="Comparison" enctype="multipart/form-data" asp-route-supplierName="@Model.SupplierName">
            <div class="container-fluid px-0">
                <div class="row full-width-row">

                    <div class="input-group">
                            <input type="file" class="form-control" id="inputGroupFile04"
                                aria-describedby="inputGroupFileAddon04" aria-label="Upload" name="file" onchange="readFile(this)">
                            <button class="btn btn-light" id=LoadButton data-loading-text="loading..." type="sumbit" value=Upload>Загрузить</button>

                            @*<button class="btn btn-primary" type="button" disabled>
                             <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                           </button>*@
                        </div>
            

                


                        <div class="form-floating" style="margin-top:5px">
                            <textarea class="form-control" disabled="true"
                                id="floatingTextarea2" style="min-height:600px;resize: none">@ViewBag.Result</textarea>
                        </div>

             
                </div>
            </div>
        </form>
    </div>
</div>